### ISSUE TITLE
START1-XS complains about disk size even though parameter is supplied

### ISSUE THREAD

**Issue by tobiasmuehl** [scaleway/docker-machine-driver-scaleway#100]
```
root@localhost:~# docker-machine create --driver scaleway --scaleway-token xxx --scaleway-organization xxx --scaleway-region ams1 --scaleway-commercial-type START1-XS --scaleway-volumes 25G sc1
Running pre-create checks...
Creating machine...
(sc1) Creating SSH key...
(sc1) Creating server...
(sc1) Starting server...
Error creating machine: Error in driver during machine creation: StatusCode: 400, Type: invalid_request_error, APIMessage: The total size of local-volume(s) of instances START1-XS must be equal to 25GB
```

Also happens with `--scaleway-volumes 25000000000`

**Comment by aurels** [comment]
Same error with the `DEV1-S`:

    docker-machine create -d scaleway --scaleway-commercial-type="DEV1-S" --scaleway-name="test" --scaleway-volumes="20G" --scaleway-debug test
    Running pre-create checks...
    Creating machine...
    (test) Creating SSH key...
    (test) Creating server...
    (test) Starting server...
    Error creating machine: Error in driver during machine creation: StatusCode: 400, Type: 
    invalid_request_error, APIMessage: The total size of local-volume(s) of instances DEV1-S must be equal to 20GB

**Comment by fullonic** [comment]
Any help from Scaleway team? @QuentinPerez @moul 

Following this blog [post](https://blog.scaleway.com/2016/docker-machine-on-scaleway/), and the [readme](https://github.com/scaleway/docker-machine-driver-scaleway/blob/master/README.md) produce the same error as describe above by @tobiasmuehl and @aurels 

There is any way to solve this issue or a workaround?
For exemple, when I run:
`docker-machine create -d scaleway  --scaleway-name="swc-docker" --scaleway-commercial-type="DEV1-S" --scaleway-volumes="20G" --scaleway-token=TOKEN --scaleway-organization=ID --scaleway-debug docker`
It create the instance volume of 20GB plus a 50GB snapshot. It's because this snapshot that the error occurs?  
Thanks

**Comment by fullonic** [comment]
running the first example:
`docker-machine create -d scaleway --scaleway-token=TOKEN --scaleway-organization=ID my-scaleway-docker-machine`

I'm getting the fellow error:
````
Running pre-create checks...
Creating machine...
(docker-test) Creating SSH key...
(docker-test) Creating server...
Error creating machine: Error in driver during machine creation: StatusCode: 403, Type: invalid_request_error, APIMessage: Quota exceeded for this resource.

**Comment by paulrostorp** [comment]
This is still happening. Could anyone from scaleway comment ?

**Comment by nitrique** [comment]
+1

**Comment by pierotofy** [comment]
+1 really confused about this :confused: 

I get multiple volumes when launching a machine and the `--scaleway-volumes` seems to be ignored?

**Comment by pierotofy** [comment]
When creating a machine via:

```
docker-machine create -d scaleway --scaleway-token=xxxxx --scaleway-organization=xxxxx --scaleway-commercial-type "GP1-XS" --scaleway-region "ams1" cloud-scaleway
```

I get multiple volumes (top two volumes in the screen below):

![image](https://user-images.githubusercontent.com/1951843/66338846-ed81d180-e90f-11e9-9a2f-237442239cfc.png)

The same machine creates via the dashboard yields a single volume of `150GB`.

**Comment by QuentinBrosse** [comment]
Hi,
Sorry for the inconvenience.

Since our new [scaleway-sdk-go](https://github.com/scaleway/scaleway-sdk-go/) is approaching a stable state, a total rewrite of the driver has begun.
It will support all instance types, fix known issues and introduce new instance features.

You can feel confident that all opened issues will be taken into account for this version 2.

Have a look at the work on #104 and the related PR: #105.

Thanks a lot for your contributions and feedback!
Stay tuned! 🤘

**Comment by tmoreira2020** [comment]
hey @QuentinBrosse, good to know that there is a working in progress to address this issue. Do you have any timeline to get a first release of the driver? I have a tight timeline to make a final decision to go with Scaleway or another docker hosting.
Thanks

**Comment by QuentinBrosse** [comment]
Hi @tmoreira2020,

I don't have a precise timeline but, in the Q1 of 2020.

**Comment by tmoreira2020** [comment]
Thanks @QuentinBrosse for the feedback, unfortunately this is too late for us to wait. As a workaround I'm thinking to patch the current version to create DEV1-S with 20GB and not 50GB. I believe 50GB is hardcoded on some place in the source code? Do you know where it is?

**Comment by tmoreira2020** [comment]
Perhaps if I hardcode 20GB in the `size` parameter do the trick here: https://github.com/scaleway/docker-machine-driver-scaleway/blob/a2f88d2c2645ef751171a954236ab4f32419b269/vendor/github.com/scaleway/scaleway-cli/pkg/api/helpers.go#L428

What do you think?
